name: script build and release
on:
	push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
	release:
		types: [published]
	# push:
	# 	branches-ignore: [master]
	# pull_request:
	# 	branches-ignore: []
jobs:
	strategy: 
		max-parallel: 1
	build:
		# - uses: actions/checkout@master
		
    runs-on: ubuntu-latest
		# runs-on: windows-latest
		# if: "! contains(toJSON(github.event.commits.*.msg), '[skip-ci]')"
		steps:  
		- name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install
		- uses: iCrawl/action-tsc@v1
		- id: build_script
		- run: tsc --build tsconfig.json 
		# - id: 
	release:
		needs: build

