on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
    - main
  release:
    types: [published]
  # push:
  # 	branches-ignore: [master]
  # pull_request:
  # 	branches-ignore: []
jobs:
  # strategy: 
  #   max-parallel: 1
  build:
    # - uses: actions/checkout@master
    
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    # if: "! contains(toJSON(github.event.commits.*.msg), '[skip-ci]')"
    steps:  
    - name: use setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: checkout project
      uses: actions/checkout@v2
    - name: install yarn
      run: npm i -g yarn
    - name: yarn install
      run: yarn install
    - name: build script
      run: yarn build
  # # publish_build:
  #   runs-on: ubuntu-latest
  #   steps:
    - name: Commit and push to main
      run: |
        git config user.email "pegak15@seznam.cz"
        git config user.name "Pegak"
        git commit -m "[Auto] Build uncompiled TS files." -a
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: main
        # branch: ${{ github.ref }}
    # needs: build

