on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
    - main
  release:
    types: [published]
  # push:
  # 	branches-ignore: [master]
  # pull_request:
  # 	branches-ignore: []
jobs:
  # strategy: 
  #   max-parallel: 1
  build:
    # - uses: actions/checkout@master
    
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    # if: "! contains(toJSON(github.event.commits.*.msg), '[skip-ci]')"
    steps:  
    - name: use setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: checkout project
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: install yarn
      run: npm i -g yarn
    - name: yarn install
      run: yarn install
    - name: build script
      run: yarn build

