on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
    - main
  release:
    types: [published]
  # push:
  # 	branches-ignore: []
jobs:
  build:
    runs-on: ubuntu-latest
    # if: "! contains(toJSON(github.event.commits.*.msg), '[skip-ci]')"
    steps:  
    - name: use setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: checkout project
      uses: actions/checkout@v2
    - name: install yarn
      run: npm i -g yarn
    - name: yarn install
      run: yarn install
    - name: build script
      run: yarn build

    - name: Commit and push to main
      run: |
        git config user.email "pegak15@seznam.cz"
        git config user.name "Pegak"
        git add .
        git commit -m "[Auto] Build uncompiled TS files." -a
        git push
